### ISSUE TITLE
Error running it

### ISSUE THREAD

**Issue by mrpingo** [thequux/wattbar#1]
Hello,

I've been searching for this for a looooong time, many thanks for bringing this to Wayland.
I am using gentoo in my laptop and installed with cargo but once I run the command in the terminal, I get the next output:

Error: invalid value: string "()", expected at least one field signature between `(` and `)`

Caused by:
    invalid value: string "()", expected at least one field signature between `(` and `)`

What can I do? Is something (a library or anything) that it depends on run?
I would do whatever test you require to test it.

Again, many thanks.

**Comment by thequux** [comment]
Huh, that's a new one. I'm pretty sure that that means that somehow UPower is presenting an invalid type signature. It's possible (and, in fact, likely) that this would be fixed by updating the zbus dependency, but that's going to take some development work on my end.

Fortunately, I planned to spend some time on wattbar this weekend anyway. I'll do that first and see whether that fixes anything; if not, we'll find something else to try.

**Comment by thequux** [comment]
It occurs to me, by the way, that the previous edition (https://github.com/thequux/xbattbar3) may work for you in the meantime. Even though it's X11-based, XWayland tends to work pretty well. That said, it fails horribly on sway, so no promises.

**Comment by mrpingo** [comment]
That's great news!

Unfortunately I am using sway, and I am still using xbattbar on xwayland that fortunately plays pretty well with it as you said.

Count on me if you need a test.

**Comment by thequux** [comment]
I've just pushed an update that should fix the dbus error you're seeing, but alas, it still doesn't work with sway 1.9 due to changes in the Wayland protocol (and/or bugs in the wayland client implementation I'm using). Unfortunately, fixing this is going to be a *big* job, as smithay-client-toolkit fundamentally changed the way that it worked, so I'll basically need to completely rewrite the graphical side of things. Software, c'est de la merde.

If you're using sway 1.8 or earlier, though, give it a go; everything seems fine there.

**Comment by mrpingo** [comment]
Many thanks for taking a look into it. And for patching it.
I wouldn't like to downgrade sway because it will brake a lot of stuff that I have that need the v1.9 and I will be forced to downgrade a bunch of packages with it. I am feeling sorry for the rewrite from scratch thingy. Indeed "c'est de la merde".

I would help with it to see it working but my coding skills is non existent but for some little mods and scripts.

Again, thanks for sharing your code with the community, thanks for taking a look and last but not less important taking your time to port it to Wayland.

If someday the planets align themselves and you have time to update it please feel free to write here so I can try it.

Kind regards

**Comment by thequux** [comment]
FWIW, I'm about 70% done with the code changes to upgrade the client toolkit; it so happens that while my desktop uses Sway 1.8, my laptop (where I actually need wattbar) is 1.9.

So that planets will come into alignment quite soon it seems :-D

**Comment by thequux** [comment]
Could you give the latest commit a check? It seems to work on my laptop with Sway 1.9, but I'd like to check it works for you before I strip out the debugging comments.

**Comment by mrpingo** [comment]
YAY!!!
You did it!!

It ran smoothly!

but.. while compiling it throwed this code (might be of your interest):

```
warning: unused import: `std::cell::Cell`
 --> src/main.rs:5:5
  |
5 | use std::cell::Cell;
  |     ^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `rc::Rc`
 --> src/main.rs:7:11
  |
7 | use std::{rc::Rc, sync::Arc};
  |           ^^^^^^

warning: unused import: `IntoColor`
  --> src/main.rs:13:26
   |
13 | use palette::{FromColor, IntoColor, LinSrgba, Mix, Oklaba, Shade, Srgba};
   |                          ^^^^^^^^^

warning: unused imports: `ZwlrLayerSurfaceV1`, `self`
  --> src/main.rs:17:29
   |
17 |     zwlr_layer_surface_v1::{self, ZwlrLayerSurfaceV1},
   |                             ^^^^  ^^^^^^^^^^^^^^^^^^

warning: variable does not need to be mutable
   --> src/main.rs:172:13
    |
172 |         let mut result = BarSurface {
    |             ----^^^^^^
    |             |
    |             help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: unused variable: `output`
   --> src/main.rs:371:78
    |
371 |     fn update_output(&mut self, _conn: &Connection, _qh: &QueueHandle<Self>, output: WlOutput) {
    |                                                                              ^^^^^^ help: if this is intentional, prefix it with an underscore: `_output`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: methods `is_horizontal`, `ccw`, and `cw` are never used
  --> src/main.rs:46:8
   |
45 | impl Side {
   | --------- methods in this implementation
46 |     fn is_horizontal(self) -> bool {
   |        ^^^^^^^^^^^^^
...
62 |     fn ccw(self) -> Self {
   |        ^^^
...
71 |     fn cw(self) -> Self {
   |        ^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: fields `output`, `side`, and `mode` are never read
   --> src/main.rs:146:5
    |
145 | pub struct BarSurface {
    |            ---------- fields in this struct
146 |     output: WlOutput,
    |     ^^^^^^
...
149 |     side: Side,
    |     ^^^^
150 |     mode: Option<Mode>,
    |     ^^^^

warning: `wattbar` (bin "wattbar") generated 8 warnings (run `cargo fix --bin "wattbar"` to apply 6 suggestions)
```

you might bump a new version.

You nailed it!
Now that it works.. I am missing the colors but this is a big step!

Again many thanks!

**Comment by thequux** [comment]
Awesome! Now to fix a crash that happens when output scale changes and rendering when the bar is on another side.

For the color issue, I've opened #2. The current scheme (blue for plugged in, traffic light gradient for battery) was suggested by Klondike quite some years ago, and I liked it so much that I never bothered to add configuration. Let me know what you'd like in that issue and I'll see what I can do.
